http:
  routers:
    server-dash-api:
      rule: "Host(`dash.pamelacoreypc.com`) && PathPrefix(`/api`)"
      entryPoints: [websecure]
      service: server-dash-api
      tls:
        certResolver: letsencrypt

    server-dash:
      rule: "Host(`dash.pamelacoreypc.com`)"
      entryPoints: [websecure]
      service: server-dash

  services:
    server-dash-api:
      loadBalancer:
        servers:
          - url: "http://server-dash-api:8080"

    server-dash:
      loadBalancer:
        servers:
          - url: "http://server-dash:80"
