import type { Project, Domain, Container, Database, Service, Alert, CleanupItem } from './types'

export const databases: Database[] = [
  {
    id: 'supa-outreach',
    name: 'supabase / outreach',
    instance: 'supabase-db',
    schema: 'outreach',
    host: 'supabase-db:5432',
    status: 'healthy',
    usedBy: ['cockpit', 'sync'],
    tables: [
      { name: 'leads',          rows: '24,312', lastWrite: '3m ago',  freshness: 'fresh' },
      { name: 'emails',         rows: '51,840', lastWrite: '3m ago',  freshness: 'fresh' },
      { name: 'inbox_threads',  rows: '3,201',  lastWrite: '12m ago', freshness: 'fresh' },
      { name: 'campaigns',      rows: '184',    lastWrite: '1h ago',  freshness: 'fresh' },
      { name: 'fathom_calls',   rows: '47',     lastWrite: '6h ago',  freshness: 'fresh' },
      { name: 'account_stats',  rows: '1,024',  lastWrite: '1h ago',  freshness: 'fresh' },
      { name: 'email_accounts', rows: '12',     lastWrite: '2h ago',  freshness: 'fresh' },
      { name: 'warmup_stats',   rows: '312',    lastWrite: '30m ago', freshness: 'fresh' },
      { name: '+ 16 more',                                            freshness: 'unknown' },
    ],
  },
  {
    id: 'supa-public',
    name: 'supabase / public',
    instance: 'supabase-db',
    schema: 'public',
    host: 'supabase-db:5432',
    status: 'warning',
    usedBy: ['signal', 'skool'],
    tables: [
      { name: 'skool_signals', rows: '1,139', lastWrite: '2h ago',   freshness: 'fresh' },
      { name: 'communities',   rows: '211',   lastWrite: '2h ago',   freshness: 'fresh' },
      { name: 'leads',         rows: '23',    lastWrite: '4d ago',   freshness: 'stale' },
      { name: 'clients',       rows: '1',     lastWrite: '4d ago',   freshness: 'stale' },
      { name: 'tg_events',     rows: '3',     lastWrite: '47d ago',  freshness: 'dead'  },
      { name: 'tg_groups',     rows: '2',     lastWrite: '47d ago',  freshness: 'dead'  },
    ],
  },
  {
    id: 'shared-icegen',
    name: 'shared-postgres / icegen',
    instance: 'shared-postgres',
    schema: undefined,
    host: 'shared-postgres:5432',
    status: 'healthy',
    usedBy: ['n8n'],
    tables: [
      { name: 'runs',        freshness: 'fresh' },
      { name: 'generations', freshness: 'fresh' },
      { name: 'leads',       freshness: 'fresh' },
      { name: 'prompts',     freshness: 'unknown' },
      { name: 'extractions', freshness: 'unknown' },
    ],
  },
  {
    id: 'shared-tg',
    name: 'shared-postgres / tg_monitoring',
    instance: 'shared-postgres',
    host: 'shared-postgres:5432',
    status: 'orphaned',
    usedBy: [],
    tables: [
      { name: 'tg_events', freshness: 'dead' },
      { name: 'tg_groups', freshness: 'dead' },
    ],
  },
  {
    id: 'n8n-db',
    name: 'n8n-postgres / n8n',
    instance: 'n8n-postgres',
    host: 'n8n-postgres:5432',
    status: 'healthy',
    usedBy: ['n8n'],
    tables: [{ name: 'internal (workflows, credentials, executions)', freshness: 'unknown' }],
  },
  {
    id: 'supa-enrichment',
    name: 'supabase / enrichment',
    instance: 'supabase-db',
    schema: 'enrichment',
    host: 'supabase-db:5432',
    status: 'warning',
    usedBy: [],
    tables: [
      { name: 'leads_master',    freshness: 'unknown' },
      { name: 'workspaces',      freshness: 'unknown' },
      { name: 'workspace_leads', freshness: 'unknown' },
      { name: 'tasks',           freshness: 'unknown' },
    ],
  },
]

export const domains: Domain[] = [
  { id: 'd-cockpit',  url: 'cockpit.pamelacoreypc.com',  target: 'outreach-cockpit:3000', traefikConfig: 'cockpit.yml', ssl: 'valid · 83d', cloudflare: true, basicAuth: false, projectId: 'cockpit' },
  { id: 'd-signal',   url: 'philippe.pamelacoreypc.com', target: 'signal-tracker:3000',   traefikConfig: 'Coolify',     ssl: 'valid',        cloudflare: true, basicAuth: false, projectId: 'signal'  },
  { id: 'd-n8n',      url: 'n8n.pamelacoreypc.com',      target: 'n8n-app:5678',          traefikConfig: 'n8n.yml',     ssl: 'valid',        cloudflare: true, basicAuth: false, projectId: 'n8n'     },
  { id: 'd-uptime',   url: 'uptime.pamelacoreypc.com',   target: 'uptime-kuma:3001',      traefikConfig: 'uptime.yml',  ssl: 'valid',        cloudflare: true, basicAuth: false, projectId: 'uptime'  },
  { id: 'd-coolify',  url: 'coolify.pamelacoreypc.com',  target: 'coolify:8000',          traefikConfig: 'Coolify',     ssl: 'valid',        cloudflare: true, basicAuth: false },
  { id: 'd-studio',   url: 'studio.pamelacoreypc.com',   target: 'supabase-studio:3000',  traefikConfig: 'studio.yml',  ssl: 'valid',        cloudflare: true, basicAuth: true  },
  { id: 'd-adminer',  url: 'adminer.pamelacoreypc.com',  target: 'adminer:8080',          traefikConfig: 'adminer.yml', ssl: 'valid',        cloudflare: true, basicAuth: true  },
  { id: 'd-supabase', url: 'supabase.pamelacoreypc.com', target: 'supabase-kong:8000',    traefikConfig: 'Coolify',     ssl: 'valid',        cloudflare: true, basicAuth: false },
]

export const containers: Container[] = [
  { id: 'c-traefik',   name: 'coolify-proxy (traefik)', status: 'healthy',  uptime: '12d',  note: 'ports 80, 443 — proxy for all domains' },
  { id: 'c-cockpit',   name: 'outreach-cockpit',        status: 'healthy',  ram: '312 MB',  cpu: '0.4%', uptime: '2d',  projectId: 'cockpit' },
  { id: 'c-cockpit-api', name: 'outreach-cockpit-api',  status: 'healthy',  ram: '180 MB',  cpu: '0.1%', uptime: '2d',  projectId: 'cockpit' },
  { id: 'c-signal',    name: 'signal-tracker',          status: 'healthy',  ram: '198 MB',  cpu: '0.2%', uptime: '5d',  projectId: 'signal'  },
  { id: 'c-n8n',       name: 'n8n-app',                 status: 'healthy',  ram: '~400 MB', cpu: '1.2%', uptime: '12d', projectId: 'n8n'     },
  { id: 'c-n8n-pg',    name: 'n8n-postgres',            status: 'healthy',  uptime: '12d',  projectId: 'n8n', note: 'internal DB' },
  { id: 'c-supa-db',   name: 'supabase-db',             status: 'healthy',  uptime: '12d',  note: 'port 5434 — main data store' },
  { id: 'c-supa-studio', name: 'supabase-studio',       status: 'healthy',  uptime: '12d'  },
  { id: 'c-supa-kong', name: 'supabase-kong',           status: 'healthy',  uptime: '12d',  note: 'API gateway' },
  { id: 'c-supa-auth', name: 'supabase-auth',           status: 'healthy',  uptime: '12d'  },
  { id: 'c-supa-rest', name: 'supabase-rest',           status: 'healthy',  uptime: '12d',  note: 'PostgREST — exposes public schema' },
  { id: 'c-shared-pg', name: 'shared-postgres',         status: 'healthy',  uptime: '12d',  note: 'port 5432 — app_admin' },
  { id: 'c-uptime',    name: 'uptime-kuma',             status: 'healthy',  uptime: '12d'  },
  { id: 'c-adminer',   name: 'adminer',                 status: 'healthy',  uptime: '25s'  },
  { id: 'c-verifier',  name: 'email-verifier',          status: 'warning',  note: 'port 8090 internal — no health check' },
]

export const projects: Project[] = [
  {
    id: 'cockpit',
    name: 'Outreach Cockpit',
    type: 'webapp',
    deployType: 'coolify',
    github: 'LeonidSvb/outreach-cockpit',
    status: 'healthy',
    domainIds: ['d-cockpit'],
    containerIds: ['c-cockpit', 'c-cockpit-api'],
    dbIds: ['supa-outreach'],
  },
  {
    id: 'signal',
    name: 'Signal Tracker',
    type: 'webapp',
    deployType: 'coolify',
    github: 'LeonidSvb/signal-tracker',
    status: 'healthy',
    domainIds: ['d-signal'],
    containerIds: ['c-signal'],
    dbIds: ['supa-public'],
  },
  {
    id: 'n8n',
    name: 'n8n',
    type: 'automation',
    deployType: 'manual',
    status: 'healthy',
    path: '/opt/compose/n8n/',
    domainIds: ['d-n8n'],
    containerIds: ['c-n8n', 'c-n8n-pg'],
    dbIds: ['n8n-db', 'shared-icegen'],
  },
  {
    id: 'sync',
    name: 'sync-data',
    type: 'cron',
    deployType: 'host',
    github: 'LeonidSvb/sync-data',
    status: 'warning',
    statusNote: 'last run 6h ago',
    path: '/opt/apps/projects/sync-data/',
    domainIds: [],
    containerIds: [],
    dbIds: ['supa-outreach'],
  },
  {
    id: 'skool',
    name: 'skool-scraper',
    type: 'cron',
    deployType: 'host',
    github: 'LeonidSvb/skool-scrape-signals',
    status: 'healthy',
    statusNote: 'last run 2h ago',
    path: '/opt/apps/projects/skool-scrape-signals/',
    domainIds: [],
    containerIds: [],
    dbIds: ['supa-public'],
  },
  {
    id: 'tg',
    name: 'tg-monitoring',
    type: 'cron',
    deployType: 'host',
    github: 'LeonidSvb/tg-monitoring',
    status: 'inactive',
    statusNote: 'last run 47 days ago',
    path: '/opt/apps/projects/tg-monitoring/',
    domainIds: [],
    containerIds: [],
    dbIds: [],
    note: 'Uses Supabase Cloud (aws) — paying for cloud unnecessarily. Consider archiving.',
  },
]

export const services: Service[] = [
  {
    id: 'svc-sync',
    name: 'sync-data',
    path: '/opt/apps/projects/sync-data/',
    github: 'LeonidSvb/sync-data',
    status: 'warning',
    statusNote: 'sync_lemlist last run 6h ago',
    scripts: [
      {
        id: 'scr-sync-lemlist',
        name: 'sync_lemlist',
        file: 'src/sync_lemlist.py',
        schedule: 'every 30m',
        source: 'Lemlist API',
        writesTo: ['outreach · leads', 'outreach · emails'],
        lastRun: '6h ago',
        lastRunStatus: 'ok',
        duration: '12s',
        records: 847,
        rate: '70/s',
        runs: [
          { id: 'sl-001', started: 'Jun 21 18:02', duration: '12s', records: 847, errors: 0, status: 'ok' },
          { id: 'sl-002', started: 'Jun 21 17:32', duration: '11s', records: 823, errors: 0, status: 'ok' },
          { id: 'sl-003', started: 'Jun 21 17:02', duration: '14s', records: 901, errors: 2, status: 'error' },
          { id: 'sl-004', started: 'Jun 21 16:32', duration: '10s', records: 780, errors: 0, status: 'ok' },
          { id: 'sl-005', started: 'Jun 21 16:02', duration: '13s', records: 812, errors: 0, status: 'ok' },
        ],
      },
      {
        id: 'scr-sync-fathom',
        name: 'sync_fathom',
        file: 'src/sync_fathom.py',
        schedule: 'every 6h',
        source: 'Fathom API',
        writesTo: ['outreach · fathom_calls'],
        lastRun: '6h ago',
        lastRunStatus: 'ok',
        duration: '3s',
        records: 47,
        runs: [
          { id: 'sf-001', started: 'Jun 21 18:00', duration: '3s', records: 47, errors: 0, status: 'ok' },
          { id: 'sf-002', started: 'Jun 21 12:00', duration: '3s', records: 45, errors: 0, status: 'ok' },
          { id: 'sf-003', started: 'Jun 21 06:00', duration: '4s', records: 49, errors: 0, status: 'ok' },
          { id: 'sf-004', started: 'Jun 21 00:00', duration: '3s', records: 43, errors: 0, status: 'ok' },
        ],
      },
      {
        id: 'scr-push-warmup',
        name: 'push_warmup',
        file: 'src/push_warmup.py',
        schedule: 'every 30m',
        source: 'Mail.so API',
        writesTo: ['outreach · warmup_stats'],
        lastRun: '30m ago',
        lastRunStatus: 'ok',
        duration: '2s',
        records: 312,
        runs: [
          { id: 'pw-001', started: 'Jun 22 09:30', duration: '2s', records: 312, errors: 0, status: 'ok' },
          { id: 'pw-002', started: 'Jun 22 09:00', duration: '2s', records: 309, errors: 0, status: 'ok' },
          { id: 'pw-003', started: 'Jun 22 08:30', duration: '3s', records: 315, errors: 0, status: 'ok' },
        ],
      },
    ],
  },
  {
    id: 'svc-skool',
    name: 'skool-scraper',
    path: '/opt/apps/projects/skool-scrape-signals/',
    github: 'LeonidSvb/skool-scrape-signals',
    status: 'healthy',
    statusNote: 'last run 2h ago',
    scripts: [
      {
        id: 'scr-skool-scraper',
        name: 'scraper',
        file: 'scraper.py',
        schedule: 'every 2h',
        source: 'skool.com',
        writesTo: ['public · skool_signals', 'public · communities'],
        lastRun: '2h ago',
        lastRunStatus: 'ok',
        duration: '45s',
        records: 1139,
        rate: '25/s',
        runs: [
          { id: 'sk-001', started: 'Jun 22 08:00', duration: '45s', records: 1139, errors: 0, status: 'ok' },
          { id: 'sk-002', started: 'Jun 22 06:00', duration: '43s', records: 1102, errors: 0, status: 'ok' },
          { id: 'sk-003', started: 'Jun 22 04:00', duration: '48s', records: 1187, errors: 3, status: 'error' },
          { id: 'sk-004', started: 'Jun 22 02:00', duration: '44s', records: 1098, errors: 0, status: 'ok' },
          { id: 'sk-005', started: 'Jun 22 00:00', duration: '46s', records: 1155, errors: 0, status: 'ok' },
        ],
      },
      {
        id: 'scr-skool-classify',
        name: 'classify',
        file: 'classify.py',
        schedule: 'every 2h (after scraper)',
        source: 'public · skool_signals',
        writesTo: ['public · skool_signals · category'],
        lastRun: '2h ago',
        lastRunStatus: 'ok',
        duration: '1m 20s',
        records: 1139,
        rate: '14/s',
        runs: [
          { id: 'cl-001', started: 'Jun 22 08:01', duration: '1m 20s', records: 1139, errors: 0, status: 'ok' },
          { id: 'cl-002', started: 'Jun 22 06:01', duration: '1m 18s', records: 1102, errors: 0, status: 'ok' },
          { id: 'cl-003', started: 'Jun 22 04:01', duration: '1m 25s', records: 1184, errors: 0, status: 'ok' },
        ],
      },
    ],
  },
  {
    id: 'svc-tg',
    name: 'tg-monitoring',
    path: '/opt/apps/projects/tg-monitoring/',
    github: 'LeonidSvb/tg-monitoring',
    status: 'inactive',
    statusNote: 'last run 47d ago',
    scripts: [
      {
        id: 'scr-tg-monitor',
        name: 'monitor',
        file: 'monitor.py',
        schedule: 'every 1h (disabled)',
        source: 'Telegram API',
        writesTo: ['supabase cloud · tg_events', 'supabase cloud · tg_groups'],
        lastRun: '47d ago',
        lastRunStatus: 'error',
        duration: '—',
        records: 0,
        runs: [
          { id: 'tg-001', started: 'May 05 10:00', duration: '2s', records: 3, errors: 1, status: 'error' },
          { id: 'tg-002', started: 'May 05 09:00', duration: '3s', records: 2, errors: 0, status: 'ok' },
        ],
      },
    ],
  },
]

export const alerts: Alert[] = [
  { id: 'a1', level: 'warning', message: 'sync-data: sync_lemlist ran 6h ago (schedule: every 30m)', targetView: 'services', targetId: 'svc-sync' },
  { id: 'a2', level: 'error',   message: 'shared-postgres / tg_monitoring: orphaned, no active project', targetView: 'databases', targetId: 'shared-tg' },
  { id: 'a3', level: 'warning', message: 'supabase / enrichment: no project writes to this DB', targetView: 'databases', targetId: 'supa-enrichment' },
  { id: 'a4', level: 'info',    message: 'tg-monitoring: inactive 47d — using Supabase Cloud unnecessarily', targetView: 'projects', targetId: 'tg' },
  { id: 'a5', level: 'warning', message: 'email-verifier: no health check configured', targetView: 'containers', targetId: 'c-verifier' },
]

export const cleanupItems: CleanupItem[] = [
  {
    id: 'cl-tg-proj',
    name: 'tg-monitoring',
    type: 'project',
    meta: 'cron · host · inactive 47d',
    reason: 'Writes to Supabase Cloud (paid). Signals now covered by skool-scraper.',
    severity: 'high',
    targetView: 'projects',
    targetId: 'tg',
  },
  {
    id: 'cl-shared-tg',
    name: 'shared-postgres / tg_monitoring',
    type: 'database',
    meta: 'shared-postgres:5432 · 2 tables · no writes',
    reason: 'Created for tg-monitoring which is now inactive. Safe to drop.',
    severity: 'high',
    targetView: 'databases',
    targetId: 'shared-tg',
  },
  {
    id: 'cl-supa-enrich',
    name: 'supabase / enrichment',
    type: 'database',
    meta: 'supabase-db:5432 · 4 tables · no writes',
    reason: 'No active project uses this schema. Likely from an old experiment.',
    severity: 'medium',
    targetView: 'databases',
    targetId: 'supa-enrichment',
  },
  {
    id: 'cl-tg-events',
    name: 'tg_events',
    type: 'table',
    meta: 'supabase / public · 3 rows · last write 47d ago',
    reason: 'Dead table from inactive tg-monitoring pipeline.',
    severity: 'medium',
    targetView: 'databases',
    targetId: 'supa-public',
  },
  {
    id: 'cl-tg-groups',
    name: 'tg_groups',
    type: 'table',
    meta: 'supabase / public · 2 rows · last write 47d ago',
    reason: 'Dead table from inactive tg-monitoring pipeline.',
    severity: 'medium',
    targetView: 'databases',
    targetId: 'supa-public',
  },
]

export const serverStats = {
  host: 'netcup-primary',
  ip: '152.53.194.162',
  location: 'Manassas, US · ARM64 8GB',
  cpu: '18%',
  ram: '4.9 / 8 GB',
  ramPct: 62,
  disk: '47 / 256 GB',
  diskPct: 18,
  uptime: '12 days',
}
